var list1 = [
  {
    id: 1,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product1.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 2,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product2.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 3,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product3.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 4,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product4.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 5,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product5.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 6,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product6.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 7,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product7.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 8,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product8.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 9,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product9.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 10,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product10.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
];







var deal = [
  {
    id: 11,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product11.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 12,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product12.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 13,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product13.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 14,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product14.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 15,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product15.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 16,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product16.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 17,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product17.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 18,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product18.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
  {
    id: 19,
    p_name: "Adult Diaper",
    tag: "Hot Seller",
    image_src: "./product_images/product19.webp",
    para: "Essecent",
    price: "499",
    price_old: "999",
    symbol: "₹",
    off: "50%",
  },
];


